repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          [
            "--profile",
            "black",
            "--settings-path",
            "backend/pyproject.toml",
            "--filter-files",
          ]
  # black
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=120
        types: [file, python]
        language_version: python3.11

  # flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120"
          - "--max-complexity=88"
          - "--select=B,C,E,F,W,T4,B9"
          - "--max-doc-length=88"
          - "--ignore=E203,E266,E501,F541,W503,W505"
  # bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-ll", "-s", "B113"]
        exclude: ^tests/
        verbose: true