"""db: v1

Revision ID: 0473a5e91523
Revises:
Create Date: 2025-03-06 18:34:54.098539

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0473a5e91523"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "care_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Enum("Ambulatory", "Stationary", name="caretype"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_care_types_created_at"), "care_types", ["created_at"], unique=False)
    op.create_index(op.f("ix_care_types_name"), "care_types", ["name"], unique=True)
    op.create_index(op.f("ix_care_types_updated_at"), "care_types", ["updated_at"], unique=False)
    op.create_table(
        "facilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("facility_zip_code", sa.String(), nullable=False),
        sa.Column("capacity_status", sa.Enum("FULL", "AVAILABLE", name="capacitytype"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_facilities_created_at"), "facilities", ["created_at"], unique=False)
    op.create_index(op.f("ix_facilities_facility_zip_code"), "facilities", ["facility_zip_code"], unique=False)
    op.create_index(op.f("ix_facilities_name"), "facilities", ["name"], unique=False)
    op.create_index(op.f("ix_facilities_updated_at"), "facilities", ["updated_at"], unique=False)
    op.create_table(
        "patients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("zip_code", sa.String(), nullable=True),
        sa.Column("care_type", sa.Enum("Ambulatory", "Stationary", name="caretype"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_patients_created_at"), "patients", ["created_at"], unique=False)
    op.create_index(op.f("ix_patients_name"), "patients", ["name"], unique=False)
    op.create_index(op.f("ix_patients_updated_at"), "patients", ["updated_at"], unique=False)
    op.create_index(op.f("ix_patients_zip_code"), "patients", ["zip_code"], unique=False)
    op.create_table(
        "facility_care_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("facility_id", sa.UUID(), nullable=False),
        sa.Column("care_type_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["care_type_id"], ["care_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["facility_id"], ["facilities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facility_id", "care_type_id", name="uq_facility_care_type"),
    )
    op.create_index(op.f("ix_facility_care_types_created_at"), "facility_care_types", ["created_at"], unique=False)
    op.create_index(op.f("ix_facility_care_types_updated_at"), "facility_care_types", ["updated_at"], unique=False)
    op.create_table(
        "zip_code_ranges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("facility_id", sa.UUID(), nullable=False),
        sa.Column("min_zip_code", sa.Integer(), nullable=False),
        sa.Column("max_zip_code", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("min_zip_code <= max_zip_code", name="valid_range"),
        sa.ForeignKeyConstraint(["facility_id"], ["facilities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_zip_code_ranges_created_at"), "zip_code_ranges", ["created_at"], unique=False)
    op.create_index(op.f("ix_zip_code_ranges_max_zip_code"), "zip_code_ranges", ["max_zip_code"], unique=False)
    op.create_index(op.f("ix_zip_code_ranges_min_zip_code"), "zip_code_ranges", ["min_zip_code"], unique=False)
    op.create_index(op.f("ix_zip_code_ranges_updated_at"), "zip_code_ranges", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_zip_code_ranges_updated_at"), table_name="zip_code_ranges")
    op.drop_index(op.f("ix_zip_code_ranges_min_zip_code"), table_name="zip_code_ranges")
    op.drop_index(op.f("ix_zip_code_ranges_max_zip_code"), table_name="zip_code_ranges")
    op.drop_index(op.f("ix_zip_code_ranges_created_at"), table_name="zip_code_ranges")
    op.drop_table("zip_code_ranges")
    op.drop_index(op.f("ix_facility_care_types_updated_at"), table_name="facility_care_types")
    op.drop_index(op.f("ix_facility_care_types_created_at"), table_name="facility_care_types")
    op.drop_table("facility_care_types")
    op.drop_index(op.f("ix_patients_zip_code"), table_name="patients")
    op.drop_index(op.f("ix_patients_updated_at"), table_name="patients")
    op.drop_index(op.f("ix_patients_name"), table_name="patients")
    op.drop_index(op.f("ix_patients_created_at"), table_name="patients")
    op.drop_table("patients")
    op.drop_index(op.f("ix_facilities_updated_at"), table_name="facilities")
    op.drop_index(op.f("ix_facilities_name"), table_name="facilities")
    op.drop_index(op.f("ix_facilities_facility_zip_code"), table_name="facilities")
    op.drop_index(op.f("ix_facilities_created_at"), table_name="facilities")
    op.drop_table("facilities")
    op.drop_index(op.f("ix_care_types_updated_at"), table_name="care_types")
    op.drop_index(op.f("ix_care_types_name"), table_name="care_types")
    op.drop_index(op.f("ix_care_types_created_at"), table_name="care_types")
    op.drop_table("care_types")
    # ### end Alembic commands ###
