"""introduce deleted_at for soft delete

Revision ID: 61c074f99078
Revises: bbec08251bf1
Create Date: 2025-03-07 19:33:37.674042

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61c074f99078"
down_revision: Union[str, None] = "bbec08251bf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("facilities", sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_index(op.f("ix_facilities_deleted_at"), "facilities", ["deleted_at"], unique=False)
    op.add_column("patients", sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_index(op.f("ix_patients_deleted_at"), "patients", ["deleted_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patients_deleted_at"), table_name="patients")
    op.drop_column("patients", "deleted_at")
    op.drop_index(op.f("ix_facilities_deleted_at"), table_name="facilities")
    op.drop_column("facilities", "deleted_at")
    # ### end Alembic commands ###
