"""add day care as caretype

Revision ID: d4f778958b60
Revises: 0473a5e91523
Create Date: 2025-03-07 18:56:57.622798

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4f778958b60"
down_revision: Union[str, None] = "0473a5e91523"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE caretype ADD VALUE 'day_care'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """psql doesn't support removing values from an enum type"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
